### ISSUE TITLE
Deploying rendezvous on kubernetes

### ISSUE THREAD

**Issue by ErikEngerd** [namespacelabs/breakpoint#14]
I would like to run the rendezvous server on kubernetes. This is of course not so trivial since rendezvous starts listening on a random port as soon as a breakpoint is started. To fix this, I want to run wstunnel (https://github.com/erebe/wstunnel) in a POD together with rendezvous. 

I already have a working wstunnel setup. Using an SSH command with a ProxyCommand option, I can connect to any SSH server in my local network, and therefore, I should be able to connect to a port on which rendezvous is listening. For instance:
1. CI job starts breakpoint
2. rendezvous server allocates random port, e.g. 6667
3. CI job logs the port number on the command line

Then I can SSH to localhost:6667 using the ProxyCommand that routes my connection through wstunnel. Since wstunnel and rendezvous are in the same POD, localhost:6667 should work. 

So far so good, this explains the setup I intend to make. It is however failing in the very first step. In concrete, I am creating a POD with rendezvous listening on UDP port 10000 and this port defined as containerPort in the POD. Then I have a service that exposes the UDP port. There appears to be a limitation in kubernetes that limits service to only one protocol type AFAIK, so I am using two services: one for the TCP service of wstunnel and one UDP service for rendezvous. Both services are LoadBalancer services.  Now I cannot get breakpoint to connect to rendezvous. 

Here is the deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wstunnel
  name: wstunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wstunnel
  template:
    metadata:
      labels:
        app: wstunnel
    spec:
      containers:
      - image: ghcr.io/erebe/wstunnel:v9.2.5
        name: wstunnel
        ports:
          - containerPort: 8080
        env:
          - name: SERVER_PROTOCOL
            value: ws
          - name: SERVER_PORT
            value: "8080"
      - image: SOMEREGISTRY/rendezvous:0.0.16 # built using the Dockerfile that comes with rendezvous
        name: rendezvous
        command:
          - /rendezvous
          - -l
          - 0.0.0.0:10000
        ports:
          - containerPort: 10000
            name: access-udp
            protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wstunnel
  name: wstunnel
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wstunnel
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.178.247
  labels:
    app: wstunnel
  name: rendezvous
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 10000
      protocol: UDP
      targetPort: 10000
      name: rendezvous-udp
  selector:
    app: wstunnel
```

Above, the wstunnel service is a cluster IP service exposed through ingress. The rendezvous service is exposed as a LoadBalancer service. I have various load balancer services already working (all using TCP).

I am using kubernetes 1.29.5 with metallb loadbalancer and Cilium CNI. 

So no connectivity from breakpoint to rendezvous. What could be wrong?
